name: Deploy Reusavel
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: the name of the deployable artifact files
                required: false
                default: dist
                type: string
        outputs:
            result:
                description: o resultado da operacao de deply
                value: ${{ jobs.deploy.outputs.outcome}}
     #   secrets:
          #  some-secret:
         #       required: false

jobs: 
    deploy:
        outputs:
         outcome: ${{ steps.set-result.outputs.step-result }}
        runs-on: ubuntu-latest
        steps:
            - name: Pegar codigo 
              uses: actions/download-artifact@v3
              with:
                name: ${{ inputs.artifact-name  }}
            - name: list files
              run: ls
            - name: Saida de informacao
              run: echo "Deployng & atualizando..." 
            - name: Setar resultado de saida
              id: set-result
              run: echo "::set-output name=step-result::success"